//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ventas()
        {
            this.Ven_prod = new HashSet<Ven_prod>();
        }
    
        public int idVenta { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idProvincia { get; set; }
        public Nullable<int> idBarrio { get; set; }
        public Nullable<int> cantidadProducto { get; set; }
        public Nullable<decimal> montoTotal { get; set; }
        public string contacto { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public string numeroTransaccion { get; set; }
        public Nullable<System.DateTime> fechaVenta { get; set; }
    
        public virtual Barrios Barrios { get; set; }
        public virtual Provincias Provincias { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ven_prod> Ven_prod { get; set; }
    }
}
